import type { Metadata } from "next";
import { Outfit, Inter } from "next/font/google";
import "../styles/tailwind.css";
import "../styles/main.scss";
import Navbar from "@/components/layout/navbar/Navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import Footer from "@/components/layout/footer/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display:"swap",
  weight:['300' , '400' , '500' , '600', '700'],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display:"swap",
  weight:['300' , '400' , '500' , '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${outfit.variable} h-full antialiased`}
    >
      <body className="bg-(--neutral-50)">
        <AppRouterCacheProvider options={{enableCssLayer:true}}>

          <Navbar />
          <main className="pt-18">

          {children}
          </main>
          <Footer />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
